rulesUrl: http://prometheus-server-here/prometheus/rules        # URL to the Status/Rules page
rulesPollingInterval: 3600                                      # Polling interval in seconds

zabbixApiUrl: https://zabbix-server-here/zabbix/api_jsonrpc.php # Full URL to your Zabbix API
zabbixApiCAFile: /etc/provisioner/ca.pem                        # If your Zabbix server use internal certificates, you can provide a CA bundle for your company (or leave it blank)
zabbixApiUser: user                                             # This can also be set via the environment variable ZABBIX_API_USER
zabbixApiPassword: password                                     # This can also be set via the environment variable ZABBIX_API_PASSWORD

zabbixKeyPrefix: prometheus                                     # Items key prefix, keys will be zabbixKeyPrefix.alertname
zabbixHost: kubernetes-cluster-prometheus                       # Name of the host that will be create
zabbixHostGroups:                                               # List of host groups for the generated host
  - Kubernetes
  - Prometheus
