# URL to the Status/Rules page
rulesUrl: http://prometheus-server-here/rules

# Polling interval in seconds
rulesPollingInterval: 3600

# Full URL to your Zabbix API
zabbixApiUrl: https://zabbix-server-here/zabbix/api_jsonrpc.php

# If your Zabbix server use internal certificates, you can provide a CA bundle for your company (or leave it blank)
zabbixApiCAFile: /etc/provisioner/ca.pem

# This can also be set via the environment variable ZABBIX_API_USER
zabbixApiUser: user

# This can also be set via the environment variable ZABBIX_API_PASSWORD
zabbixApiPassword: password

# Zabbix items key prefix, keys will be zabbixKeyPrefix.alertname
zabbixKeyPrefix: prometheus

# List of host configuration
zabbixHosts:
  # Name of the host in zabbix
  - name: gmauleon-test01
    # Key/Value pairs that must be present on a prometheus rule in order for it to be selected for that host
    selector:
      zabbix: gmauleon-test01
    # List of host groups the host will belong to
    hostGroups:
      - kubernetes
      - prometheus
    # tag and deploymentStatus are inventory fields currently supported for an host
    tag: RDV
    deploymentStatus: 0
    # itemDefault* below, defines item values when not specified in a rule
    itemDefaultApplication: prometheus
    # For history and trends in zabbix 2.x you have to put those in days like 7 or 90
    itemDefaultHistory: 5d
    itemDefaultTrends: 190d
    itemDefaultTrapperHosts: 0.0.0.0/32 # Hosts permitted to send data (your webhook external CIDR, default is from everywhere)
  - name: gmauleon-test02
    selector:
      zabbix: gmauleon-test02
    hostGroups:
      - kubernetes
      - gmauleon
    itemDefaultApplication: test
    itemDefaultHistory: 7d
    itemDefaultTrends: 190d
    itemDefaultTrapperHosts: 0.0.0.0/32
